# Generated by Django 5.2.7 on 2025-10-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0002_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="middle_name",
            field=models.CharField(default="MiddleName", max_length=255),
            preserve_default=False,
        ),
    ]
